# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "02969e11d7c2f615355bdd86114f6af3"
name = "app-template-remix"
handle = "app-template-remix-5"
application_url = "https://example.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "quickstart-7683b804.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
